
language: node_js
node_js:
  - node
  - lts/*
install:
  - npm install
script:
  - npm run lint:styles
  - npm run lint:js
  - npm run lint:html
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
node: 'lts/*